In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [4]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [7]:
A = np.random.randn(10)

A

array([-0.64148075, -1.70133278,  2.87063663, -0.4954739 ,  1.28876825,
       -0.17607364,  0.63046515, -2.37663426,  1.21474186,  0.75681103])

In [10]:
B = np.random.randn(10)

In [11]:
np.maximum(A,B)

array([-0.64148075, -0.95727921,  2.87063663, -0.05778145,  1.28876825,
        0.80955767,  0.92623707, -0.37293387,  1.21474186,  1.00781488])

In [12]:
np.add(A,B)

array([-2.35420011, -2.65861199,  3.51393184, -0.55325534,  2.19254004,
        0.63348402,  1.55670222, -2.74956814,  1.92332666,  1.76462591])

In [13]:
website = 'http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs'
import webbrowser
webbrowser.open(website)

True